### ISSUE TITLE
Blazor App - No HTTPS

### ISSUE THREAD

**Issue by ajobbins** [isaacrlevin/PresenceLight#149]
When I launched the app for the first time, it runs http on port 5000 but an error message was shown saying "Failed to determine the https port". Nothing was running on port 5001, so the app fails in the browser when run as it cannot redirect back to localhost:5001.

info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: ******\Downloads\PresenceLight
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.

Now when I run PresenseLight.exe there is no error or message about https, and nothing runs on port 5001 so it just doesn't work. I checked NetStat and nothing else is using those ports.

After loading the page at http://localhost:5000 I get a Microsoft error AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application

## Further details
- OS: Windows 10 Pro
- PresenceLight App Type: Blazor
- PresenceLight Build: ?
- PresenceLight Version: 3.0.46
- Did you clear settings.json? Doesn't seem to exist
- ASP.NET Core version: Unsure

**Comment by isaacrlevin** [comment]
Try to remove this code from program.cs

     .ConfigureWebHostDefaults(webBuilder =>
                   {
                       webBuilder
                       .ConfigureKestrel(options =>
                       {
                           if (Convert.ToBoolean(configForMain["DeployedToServer"]))
                           {
                               var server = Dns.GetHostName();
                               IPHostEntry heserver = Dns.GetHostEntry(server);
                               var ip = heserver.AddressList.Where(a => a.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork).FirstOrDefault();

                               if (ip != null)
                               {
                                   options.Listen(ip, 5001);
                                   options.Listen(ip, 5002, listenOptions =>
                                   {
                                       listenOptions.UseHttps();
                                       listenOptions.UseHttps("presencelight.pfx", "presencelight");
                                   });

                               }
                           }
                           if (Convert.ToBoolean(configForMain["DeployedToContainer"]))
                           {
                               options.ConfigureHttpsDefaults(listenOptions =>
                               {
                                   listenOptions.SslProtocols = SslProtocols.Tls12;
                               });
                           }
                       });

**Comment by ross-p-smith** [comment]
I had a similar issue until I changed the Debug Profile to the PresenceLight.Worker

**Comment by isaacrlevin** [comment]
This should be fixed in main now

**Comment by ajobbins** [comment]
Have downloaded 3.0.56 but still have the same issue, plus some new warns

info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\******\Apps\PresenceLight
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
warn: Microsoft.AspNetCore.Http.ResponseCookies[1]
      The cookie '.AspNetCore.OpenIdConnect.Nonce.CfDJ8K4*****lWX1qc' has set 'SameSite=None' and must also set 'Secure'.
warn: Microsoft.AspNetCore.Http.ResponseCookies[1]
      The cookie '.AspNetCore.Correlation.4EHRwKf-****a1IZJ5hAvhA' has set 'SameSite=None' and must also set 'Secure'.

**Comment by isaacrlevin** [comment]
run a dotnet --info and tell me what the value of your appsettings.json?
