### ISSUE TITLE
"Use Activity Status" not working for LIFX

### ISSUE THREAD

**Issue by patrimal** [isaacrlevin/presencelight#328]
Very excited to see the "Use Activity Status" settings! Is this wired up for LIFX? It seems like it's being ignored and the colors being used are the availability ones. 

I'm on Nightly 4.1.36.0.

**Comment by isaacrlevin** [comment]
This is fixed in latest nightly

**Comment by patrimal** [comment]
Thanks for taking a look, Isaac. I am still seeing the same behavior in 4.1.41.0. I check the "Use Activity Status" in the LIFX tab, configure colors and hit save, but nothing changes. When I change colors in the with that checkbox unchecked (so, using availability), my color selections are properly reflected.

**Comment by patrimal** [comment]
I tried a few of the main ones (Available, Away, Busy, In A Call) and none of them seem to work

**Comment by isaacrlevin** [comment]
Can you try the latest nightly? I just pushed what I think is a fix

**Comment by isaacrlevin** [comment]
confirmed works, closing
