### ISSUE TITLE
Repeated request for authentication

### ISSUE THREAD

**Issue by warthurton** [isaacrlevin/PresenceLight#76]
Each time I launch PresenceLight it re-authenticate via the web browser.

I have tried uninstalling and reinstalling. I have installed 2.0.69.0 using the appxbundle.

Where are the credentials stored so I can clear them completely and see if I can get it to save?

**Comment by isaacrlevin** [comment]
hmmm odd, here is the token area. If you have issues let me know
C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A_zfcjmmeb3zeaa\LocalState\token.json

**Comment by sborg-ms** [comment]
Oh I get that also - I thought that was expected on restart  (which is a pain but thought it was needed!)... I have the token file as noted but it does prompt on every restart.

**Comment by warthurton** [comment]
I wiped that whole 37828IssacLevin directory and still get the same result.  Could our organization disallow storage of cached credentials?  I'll d/l the code later and trace the run.

**Comment by isaacrlevin** [comment]
All the code to do this is in SettingsService. I try to create the file where the exe is (program files) and if that fails I fall back to local storage. I can take a look and see what happens attaching to VS

**Comment by sborg-ms** [comment]
2.0.75.0 - still prompts for auth on every start of the app.

**Comment by isaacrlevin** [comment]
I will need to wait to test as VS Attach to deployed WPF isn't working quite right with .NET 5

**Comment by warthurton** [comment]
It might be the Azure AD permissions granted when the app is installed from the package / store.  I wonder if the cause is the conditional policy setup by our org for MFA.

**Comment by isaacrlevin** [comment]
@warthurton any update?

**Comment by thoemmi** [comment]
The same happens for me. However, I've installed PresenceLight via chocolatey, so I guess it's not related to the Microsoft Store.

**Comment by isaacrlevin** [comment]
Installed the same way. @thoemmi have you looked at the token file mentioned above?

**Comment by warthurton** [comment]
> @warthurton any update?

I'm having problems getting it to work when I compile myself.  I have been swamped lately so I haven't been able to spend as much time working on it as I wish.

**Comment by thoemmi** [comment]
@isaacrlevin Yes, there's a toke.json. However, it's a binary file, so I cannot read its content.

**Comment by isaacrlevin** [comment]
This is now fixed in Nightly. The token is moved to a location that PresenceLight has guaranteed write access to.

**Comment by isaacrlevin** [comment]
@thoemmi can you validate?

**Comment by thoemmi** [comment]
Unfortunately, 3.0.5 does not fix the issue. May I should give the Microsoft Store version a try?

**Comment by isaacrlevin** [comment]
3.0.13 is the one you want. Available by nightly install

**Comment by thoemmi** [comment]
I can confirm that 3.0.13 fixed the issue :+1:

**Comment by warthurton** [comment]
Sorry for the delay. I also can confirm resolution of the error.
